# Source: cluster-api-byoh/templates/machinedeployment.yaml
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: 45e151c6-md-tks
  namespace: 45e151c6
spec:
  template:
    spec: {}
